name: Vercel Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # required
          vercel-args: '--prod'
          scope: ${{ secrets.VERCEL_SCOPE }}
